target_model:
  model_name_or_path: deepseek-chat
  base_url: https://api.deepseek.com/v1
  token:
  temperature: 0.5
  max_n_tokens: 1200

judge_model:
  model_name_or_path: deepseek-chat
  base_url: https://api.deepseek.com/v1
  token:
  max_n_tokens: 50

attack:
  max_retries: 5
  cutoff_score: 9
  judge_max_n_tokens: 10

input:
  targets_path: 

output:
  output_file: tsa_results_miniHarmBench_deepseek.json
  live_file: tsa_live_results_miniHarmBench_deepseek.jsonl
  save_all_to_json: true
  output_dir: output

resume:
  auto_resume: true
  start_index: null
  end_index: null
